---
  title: "R Data Types and Data Structures"
output:
  html_document:
  df_print: paged
editor_options:
  chunk_output_type: console
---
  
  **First line**
```{r}
p = matrix(nrow = 5,ncol = 2,c(0.95,0.95,0.9,0.9,0.8,0.05,0.05,0.1,0.1,0.2))
print(p)
```


```{r}
p[1,]
```

```{r}
s=c(1,0)
print(s)
```

```{r}
sample(s,size = 1,prob = c(0.95,0.05))

```
```{r}
sample(s,size = 100,replace = TRUE, prob = c(0.95,0.05))9
```

```{r}
sample(s, size = 100, replace = TRUE, prob = p[1, ])
```
**How to write for loop**
```{r}
s=c(1,0)
for (j in c(1:5)) {
  print(j)
}
```
**How to create empty vector**
```{r}
numeric(10)
```
```{r}
# how to user define function
my_function = function(data){
  return(sum(data)>3)
}
```
```{r}
my_function(p)
```
**Judging the judge function**
```{r}
judgeResult = function(){
  results = numeric(5)
  for (j in c(1:5)) {
   results[j]= sample(s, size = 1,prob = p[j, ])
  }
  return(results)
}
```
** Scenario where judge e copy judge a**
```{r}
#judgeResult = function(){
#  results = numeric(5)
#  for (j in c(1:4)) {
#    results[j]= sample(s, size = 1,prob = p[j, ])
 # }
#  results[5]==results[1]
#  return(results)
#}
```

**Check Judges decision**

```{r}
judgeResult()
```

```{r}
b=replicate(10,judgeResult())
rownames(b)=c("Judge A","Judge B","Judge C","Judge D","Judge E")
print(b)

```
```{r}
nsimuationss=100000 #100 simulation of Judges results
simulatedData = replicate(nsimuationss,judgeResult())
rownames(simulatedData)=c("Judge A","Judge B","Judge C","Judge D","Judge E")
print(simulatedData)
simulatedData[,1:10]
```
```{r}
checkEvent = function(data){
  return(sum(data)< 3)
}
checkEvent(simulatedData[,1])
```
```{r}
apply(simulatedData, 2, checkEvent)
```

```{r}
sum(apply(simulatedData, 2, checkEvent))

```

```{r}
mean(apply(simulatedData,2,checkEvent))
```




  